# Similarities between combinations

## 1. Data import

In [7]:
import pandas as pd
import numpy as np

In [8]:
# Load niaid queries
queries_df = pd.read_csv('./niaid_queries.csv', sep=',')
queries_df

         combination search term                                   result id
0     original query   influenza                                 PRJNA658522
1     original query   influenza                                 PRJNA658529
2     original query   influenza                                 PRJNA658552
3     original query   influenza                                 PRJNA658564
4     original query   influenza                                 PRJNA658562
...              ...         ...                                         ...
3995             c15         hiv  VIVLI_02021d26-0e96-424c-8fec-77cbd204fd8d
3996             c15         hiv  VIVLI_7a8a7234-ada3-465b-a608-347b5e74a542
3997             c15         hiv  VIVLI_7ac8687d-79c8-4860-8141-83776849e2df
3998             c15         hiv  VIVLI_242c4b5a-19b3-4a51-b885-05358ed89db6
3999             c15         hiv                Dataverse_10.7910_DVN_OVEAC9

[4000 rows x 3 columns]

In [9]:
queries_df['search term'].unique()

array(['influenza', 'malaria therapeutics', 'long covid',
       'zika microcephaly', 'naegleria fowleri infection', 'asthma',
       'allergy treatment', 'allergen skin prick test',
       'sublingual immunotherapy', 'AIDS', 't-cell function',
       'immunotherapeutics', "addison's disease", 'cancer',
       'myocardial infarction', 'rational cancer drug design',
       'dendritic cells', 'mast cells', 'plasmacytoid dendritic cells',
       'pinealocyte', 'metabolomics', 'gwas', 'tuberculin skin test',
       'mycobacterium', 'hiv'], dtype=object)

## 2. Data wrangling

In [10]:
# Remove unneeded rows
combinations_df = queries_df.drop(
                    queries_df.loc[queries_df['combination'] == 'original query'].index).copy(deep = True)
combinations_df

     combination search term                                   result id
10            c1   influenza                                 PRJNA658522
11            c1   influenza                                 PRJNA658529
12            c1   influenza                                 PRJNA658552
13            c1   influenza                                 PRJNA658564
14            c1   influenza                                 PRJNA658562
...          ...         ...                                         ...
3995         c15         hiv  VIVLI_02021d26-0e96-424c-8fec-77cbd204fd8d
3996         c15         hiv  VIVLI_7a8a7234-ada3-465b-a608-347b5e74a542
3997         c15         hiv  VIVLI_7ac8687d-79c8-4860-8141-83776849e2df
3998         c15         hiv  VIVLI_242c4b5a-19b3-4a51-b885-05358ed89db6
3999         c15         hiv                Dataverse_10.7910_DVN_OVEAC9

[3750 rows x 3 columns]

## 3. Similarity computation using the Jaccard index

In [11]:
# Create sets of result ids for each combination
sets = combinations_df.groupby('combination')['result id'].apply(set)

# Jaccard similarity between sets
def jaccard_similarity(set1, set2):
    intersection = len(set1.intersection(set2))
    union = len(set1.union(set2))
    return intersection / union

# Calculate similarities
similarities = {}
for combi1 in sets.index:
    for combi2 in sets.index:
        if combi1 != combi2 and (combi2, combi1) not in similarities:
            similarity = jaccard_similarity(sets[combi1], sets[combi2])
            similarities[(combi1, combi2)] = similarity

print("\nJaccard similarities:")
for (combi1, combi2), similarity in similarities.items():
    print(f"Similarity between set_{combi1} and set_{combi2}: {similarity}")

Jaccard similarities:
Similarity between set_c1 and set_c10: 0.3028720626631854
Similarity between set_c1 and set_c11: 0.8587360594795539
Similarity between set_c1 and set_c12: 0.7361111111111112
Similarity between set_c1 and set_c13: 0.5625
Similarity between set_c1 and set_c14: 0.42165242165242167
Similarity between set_c1 and set_c15: 0.3351206434316354
Similarity between set_c1 and set_c2: 0.7241379310344828
Similarity between set_c1 and set_c3: 0.5290519877675841
Similarity between set_c1 and set_c4: 0.38227146814404434
Similarity between set_c1 and set_c5: 0.2794871794871795
Similarity between set_c1 and set_c6: 0.9455252918287937
Similarity between set_c1 and set_c7: 0.7421602787456446
Similarity between set_c1 and set_c8: 0.5290519877675841
Similarity between set_c1 and set_c9: 0.40168539325842695
Similarity between set_c10 and set_c11: 0.3028720626631854
Similarity between set_c10 and set_c12: 0.3633879781420765
Similarity between set_c10 and set_c13: 0.4590643274853801
Similarity between set_c10 and set_c14: 0.5611285266457681
Similarity between set_c10 and set_c15: 0.6622073578595318
Similarity between set_c10 and set_c2: 0.4096045197740113
Similarity between set_c10 and set_c3: 0.5545171339563862
Similarity between set_c10 and set_c4: 0.6996587030716723
Similarity between set_c10 and set_c5: 0.7785714285714286
Similarity between set_c10 and set_c6: 0.2994791666666667
Similarity between set_c10 and set_c7: 0.39385474860335196
Similarity between set_c10 and set_c8: 0.5167173252279635
Similarity between set_c10 and set_c9: 0.6938775510204082
Similarity between set_c11 and set_c12: 0.7361111111111112
Similarity between set_c11 and set_c13: 0.5772870662460567
Similarity between set_c11 and set_c14: 0.43804034582132567
Similarity between set_c11 and set_c15: 0.36065573770491804
Similarity between set_c11 and set_c2: 0.6556291390728477
Similarity between set_c11 and set_c3: 0.4925373134328358
Similarity between set_c11 and set_c4: 0.35597826086956524
Similarity between set_c11 and set_c5: 0.2729591836734694
Similarity between set_c11 and set_c6: 0.9011406844106464
Similarity between set_c11 and set_c7: 0.7123287671232876
Similarity between set_c11 and set_c8: 0.5384615384615384
Similarity between set_c11 and set_c9: 0.41761363636363635
Similarity between set_c12 and set_c13: 0.7543859649122807
Similarity between set_c12 and set_c14: 0.5741324921135647
Similarity between set_c12 and set_c15: 0.4476744186046512
Similarity between set_c12 and set_c2: 0.7667844522968198
Similarity between set_c12 and set_c3: 0.5772870662460567
Similarity between set_c12 and set_c4: 0.42165242165242167
Similarity between set_c12 and set_c5: 0.3271276595744681
Similarity between set_c12 and set_c6: 0.7301038062283737
Similarity between set_c12 and set_c7: 0.8656716417910447
Similarity between set_c12 and set_c8: 0.6501650165016502
Similarity between set_c12 and set_c9: 0.5030120481927711
Similarity between set_c13 and set_c14: 0.7386759581881533
Similarity between set_c13 and set_c15: 0.5759493670886076
Similarity between set_c13 and set_c2: 0.7064846416382252
Similarity between set_c13 and set_c3: 0.7064846416382252
Similarity between set_c13 and set_c4: 0.5353846153846153
Similarity between set_c13 and set_c5: 0.39775910364145656
Similarity between set_c13 and set_c6: 0.5625
Similarity between set_c13 and set_c7: 0.7421602787456446
Similarity between set_c13 and set_c8: 0.8050541516245487
Similarity between set_c13 and set_c9: 0.630718954248366
Similarity between set_c14 and set_c15: 0.75
Similarity between set_c14 and set_c2: 0.5496894409937888
Similarity between set_c14 and set_c3: 0.6915254237288135
Similarity between set_c14 and set_c4: 0.5961538461538461
Similarity between set_c14 and set_c5: 0.4604105571847507
Similarity between set_c14 and set_c6: 0.42165242165242167
Similarity between set_c14 and set_c7: 0.5691823899371069
Similarity between set_c14 and set_c8: 0.7326388888888888
Similarity between set_c14 and set_c9: 0.7412587412587412
Similarity between set_c15 and set_c2: 0.4393063583815029
Similarity between set_c15 and set_c3: 0.5859872611464968
Similarity between set_c15 and set_c4: 0.6241830065359477
Similarity between set_c15 and set_c5: 0.5339506172839507
Similarity between set_c15 and set_c6: 0.3387096774193548
Similarity between set_c15 and set_c7: 0.4518950437317784
Similarity between set_c15 and set_c8: 0.5910543130990416
Similarity between set_c15 and set_c9: 0.7317073170731707
Similarity between set_c2 and set_c3: 0.7064846416382252
Similarity between set_c2 and set_c4: 0.5167173252279635
Similarity between set_c2 and set_c5: 0.36712328767123287
Similarity between set_c2 and set_c6: 0.7006802721088435
Similarity between set_c2 and set_c7: 0.8867924528301887
Similarity between set_c2 and set_c8: 0.7123287671232876
Similarity between set_c2 and set_c9: 0.544891640866873
Similarity between set_c3 and set_c4: 0.7326388888888888
Similarity between set_c3 and set_c5: 0.5075528700906344
Similarity between set_c3 and set_c6: 0.5151515151515151
Similarity between set_c3 and set_c7: 0.6447368421052632
Similarity between set_c3 and set_c8: 0.8382352941176471
Similarity between set_c3 and set_c9: 0.7508771929824561
Similarity between set_c4 and set_c5: 0.6767676767676768
Similarity between set_c4 and set_c6: 0.3708791208791209
Similarity between set_c4 and set_c7: 0.471976401179941
Similarity between set_c4 and set_c8: 0.630718954248366
Similarity between set_c4 and set_c9: 0.7722419928825622
Similarity between set_c5 and set_c6: 0.2729591836734694
Similarity between set_c5 and set_c7: 0.3523035230352303
Similarity between set_c5 and set_c8: 0.45481049562682213
Similarity between set_c5 and set_c9: 0.5910543130990416
Similarity between set_c6 and set_c7: 0.7241379310344828
Similarity between set_c6 and set_c8: 0.524390243902439
Similarity between set_c6 and set_c9: 0.40168539325842695
Similarity between set_c7 and set_c8: 0.718213058419244
Similarity between set_c7 and set_c9: 0.5401234567901234
Similarity between set_c8 and set_c9: 0.7386759581881533